### ISSUE TITLE
Fury website does not have any obvious links to mailing lists

### ISSUE THREAD

**Issue by sebbASF** [apache/incubator-fury-site#131]
Users and developers should be able to easily find how to contact the project

**Comment by chaokunyang** [comment]
We have en email at page footer:
![image](https://github.com/apache/incubator-fury-site/assets/12445254/97cbc09a-7d69-430f-8393-7e4908c9ebdf)

You mean we should have something like:
![image](https://github.com/apache/incubator-fury-site/assets/12445254/8b7374ab-0958-46df-ab36-7f3f68bcdecd)

**Comment by chaokunyang** [comment]
Hi @sebbASF , I add community page in #133 , could you help review it?

**Comment by chaokunyang** [comment]
Good suggestion, updated to:
![image](https://github.com/apache/incubator-fury-site/assets/12445254/09efafa8-690b-4359-b16c-346f30b39675)
